# Shell variables
# Generated by 'wal'
wallpaper='/home/vagahbond/.config/sway/config.d/wallpaper.jpg'

# Special
background='#050505'
foreground='#dbd6cf'
cursor='#dbd6cf'

# Colors
color0='#050505'
color1='#9E4427'
color2='#927061'
color3='#A58975'
color4='#6C7C81'
color5='#6A9599'
color6='#A0A29C'
color7='#dbd6cf'
color8='#999590'
color9='#9E4427'
color10='#927061'
color11='#A58975'
color12='#6C7C81'
color13='#6A9599'
color14='#A0A29C'
color15='#dbd6cf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
