--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/vagahbond/.config/sway/config.d/wallpaper.jpg"

-- Special
background="#050505"
foreground="#dbd6cf"
cursor="#dbd6cf"

-- Colors
color0="#050505"
color1="#9E4427"
color2="#927061"
color3="#A58975"
color4="#6C7C81"
color5="#6A9599"
color6="#A0A29C"
color7="#dbd6cf"
color8="#999590"
color9="#9E4427"
color10="#927061"
color11="#A58975"
color12="#6C7C81"
color13="#6A9599"
color14="#A0A29C"
color15="#dbd6cf"
